/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_ujm_tse_lt2c_satin_cache_size_CacheSize */

#ifndef _Included_fr_ujm_tse_lt2c_satin_cache_size_CacheSize
#define _Included_fr_ujm_tse_lt2c_satin_cache_size_CacheSize
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray JNICALL Java_fr_ujm_tse_lt2c_satin_cache_size_CacheSize_getCPUCacheInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
